name: Build and Publish Uber JAR

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          distribution: temurin
          java-version: 8

      - name: Build and Test
        run: sbt -v +test

      - name: Build Uber JAR
        run: sbt assembly

      - name: Get Version
        id: version
        run: echo ::set-output name=snapshot::$(sbt -no-colors 'print version' | tail -n 1)

      - name: Show Version
        run: echo $(sbt -no-colors 'print version' | tail -n 1)

      - name: Output Version
        run: echo "JAR_VERSION=${{ steps.version.outputs.snapshot }}" >> $GITHUB_ENV

      - name: Publish Uber JAR
        uses: actions/upload-artifact@v2
        with:
          name: spark-pinecone-uber-jar-${{ env.JAR_VERSION }}.jar
          path: /home/runner/work/spark-pinecone/target/scala-2.12/spark-pinecone-${{ env.JAR_VERSION }}.jar

